//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.14 at 10:06:06 PM CEST 
//


package it.polimi.modaclouds.space4cloud.line;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polimi.modaclouds.space4cloud.line package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polimi.modaclouds.space4cloud.line
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Percentile }
     * 
     */
    public Percentile createPercentile() {
        return new Percentile();
    }

    /**
     * Create an instance of {@link SEFF }
     * 
     */
    public SEFF createSEFF() {
        return new SEFF();
    }

    /**
     * Create an instance of {@link ResponseTimeDistribution }
     * 
     */
    public ResponseTimeDistribution createResponseTimeDistribution() {
        return new ResponseTimeDistribution();
    }

    /**
     * Create an instance of {@link Station }
     * 
     */
    public Station createStation() {
        return new Station();
    }

    /**
     * Create an instance of {@link Workload }
     * 
     */
    public Workload createWorkload() {
        return new Workload();
    }

    /**
     * Create an instance of {@link Processor }
     * 
     */
    public Processor createProcessor() {
        return new Processor();
    }

    /**
     * Create an instance of {@link CmcqnModel }
     * 
     */
    public CmcqnModel createCmcqnModel() {
        return new CmcqnModel();
    }

}
