//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.13 at 01:26:08 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.modaclouds.eu/xsd/2013/6/lineResult", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.polimi.modaclouds.space4cloud.line;
