<<<<<<< HEAD
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.06 at 08:39:20 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.modaclouds.eu/xsd/2013/6/lineResult", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.polimi.modaclouds.space4cloud.line;
=======
//
// Questo file è stato generato dall'architettura JavaTM per XML Binding (JAXB) Reference Implementation, v2.2.7 
// Vedere <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Qualsiasi modifica a questo file andrà persa durante la ricompilazione dello schema di origine. 
// Generato il: 2014.05.25 alle 05:56:44 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.modaclouds.eu/xsd/2013/6/lineResult", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.polimi.modaclouds.space4cloud.line;
>>>>>>> branch 'master' of https://github.com/deib-polimi/modaclouds-space4cloud.git
